CREATE DATABASE IF NOT EXISTS DIGITALLIBRARY;
USE DIGITALLIBRARY;
CREATE TABLE IF NOT EXISTS BOOKS(
BOOK_ID INT PRIMARY KEY,
TITLE VARCHAR(100),
CATEGORY VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS STUDENTS(
STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR(100),
LAST_DATE_OF_BORROWED DATE
);
CREATE TABLE IF NOT EXISTS ISSUEDBOOKS(
ISSUE_ID INT PRIMARY KEY,
BOOK_ID INT,
STUDENT_ID INT,
ISSUE_DATE DATE,
RETURN_DATE DATE,
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);
INSERT ignore INTO BOOKS VALUES
(1,'JAVA','EDUCATION'),
(2,'PYTHON','EDUCATION'),
(3,'SQL','EDUCATION'),
(4,'PHYSICS','SCIENCE');
INSERT IGNORE INTO STUDENTS VALUES
(101,'TEJASWINI','2025-01-15'),
(102,'YESHWANTH','2025-11-14'),
(103,'YASHWANTH','2025-06-30');

INSERT IGNORE INTO ISSUEDBOOKS VALUES
(1,1,101,'2025-01-20',NULL),
(2,2,102,'2025-11-25','2025-04-05');

SELECT 
	S.NAME,
    B.TITLE,
    I.ISSUE_DATE,
    GREATEST(DATEDIFF(CURDATE(),I.ISSUE_DATE)-14,0) AS OVERDUE_DAYS,
    GREATEST(DATEDIFF(CURDATE(), I.ISSUE_DATE) -14,0) *5 AS PENALTY
FROM ISSUEDBOOKS I
JOIN STUDENTS S ON I.STUDENT_ID = S.STUDENT_ID
JOIN BOOKS B ON I.BOOK_ID = B.BOOK_ID
WHERE I.RETURN_DATE IS NULL
AND I.ISSUE_DATE < CURDATE() - INTERVAL 14 DAY;

SELECT 
	 B.CATEGORY ,
     COUNT(*) AS TOTAL_BORROWED
FROM ISSUEDBOOKS I
JOIN BOOKS B ON I.BOOK_ID =B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY TOTAL_BORROWED DESC;

SET SQL_SAFE_UPDATES=0;
DELETE FROM STUDENTS
WHERE LAST_DATE_OF_BORROWED < CURDATE() - INTERVAL 3 YEAR;
SET SQL_SAFE_UPDATES = 1;