DROP DATABASE IF EXISTS RETAIL_SALES_DATABASE;
CREATE DATABASE RETAIL_SALES_DATABASE;
USE RETAIL_SALES_DATABASE;
CREATE TABLE IF NOT EXISTS CUSTOMERS(
	CUST_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CITY VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS PRODUCTS(
	PROD_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    PRICE DECIMAL(10,2)
);
CREATE TABLE IF NOT EXISTS ORDERS(
	ORDER_ID INT PRIMARY KEY,
    CUST_ID INT,
    ORDER_DATE DATE,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID)
    );
CREATE TABLE IF NOT EXISTS ORDER_ITEMS(
	ORDER_ID INT,
    PROD_ID INT,
    QUANTITY INT,
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY(PROD_ID) REFERENCES PRODUCTS(PROD_ID)
    );
INSERT INTO CUSTOMERS VALUES(1,'TEJASWINI','HYDERABAD'),
(2,'YESHWANTH','BANGLORE'),
(3,'YASHWANTH','CHENNAI');
INSERT INTO PRODUCTS VALUES
(1001,'MOUSE','ELECTRONICS',5000),
(1002,'KEYBOARD','ELECTRONICS',5500),
(1003,'SHIRT','FASHION',3000);
INSERT INTO ORDERS VALUES
(101,1,'2026-04-12'),
(102,2,'2025-05-15'),
(103,3,'2026-04-05');
INSERT INTO ORDER_ITEMS VALUES
(101,1001,1),
(102,1002,2),
(103,1003,3),
(101,1002,2);

SELECT P.NAME, SUM(OI.QUANTITY) AS TOTAL FROM ORDER_ITEMS OI JOIN PRODUCTS P ON OI.PROD_ID = P.PROD_ID group by P.NAME ORDER BY TOTAL DESC;

SELECT C.NAME,SUM(P.PRICE*OI.QUANTITY) AS TOTAL_SPENT FROM CUSTOMERS C JOIN ORDERS O ON C.CUST_ID = O.CUST_ID
JOIN ORDER_ITEMS OI ON O.ORDER_ID=OI.ORDER_ID
JOIN PRODUCTS P ON OI.PROD_ID = P.PROD_ID GROUP BY C.NAME ORDER BY TOTAL_SPENT DESC;

select date_format(o.order_date,'%Y-%M') as month,sum(p.price*oi.quantity) as revenue from orders o join order_items oi on o.order_id = oi.order_id join products p on oi.prod_id=p.prod_id group by month order by month;

select p.category , sum(p.price*oi.quantity) as total_sales from products p join order_items oi on p.prod_id = oi.prod_id group by p.category;

select c.cust_id,c.name from customers c left join orders o on c.cust_id=o.cust_id where o.order_id is null;
    